server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    relaxed-query-chars: '|,{,},[,],^,`,<,>,\,;,/,?,@,#,$,%,&,=,+'
    relaxed-path-chars: '|,{,},[,],^,`,<,>,\,;,/,?,@,#,$,%,&,=,+'

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


config:
  import: optional:file:.env[.properties]


web:
  resources:
    add-mappings: false


spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: packet-anomaly-detection


  datasource:
    url: ${URL}
    username: ${USER_NAME}
    password: ${PASS_WORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    com.security.monitor: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log



monitoring:
# 위협 탐지 기준 설정
  detection:
    traffic-spike-threshold: 1000
    port-scan-threshold: 10
    large-packet-threshold: 1500
    connection-attempt-threshold: 50


# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html